// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: documents.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addCollaborator = `-- name: AddCollaborator :one
INSERT INTO DocumentCollaborators(document_id, collaborator_id)
VALUES ($1, $2)
RETURNING 1
`

type AddCollaboratorParams struct {
	DocumentID     uuid.NullUUID
	CollaboratorID uuid.NullUUID
}

func (q *Queries) AddCollaborator(ctx context.Context, arg AddCollaboratorParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addCollaborator, arg.DocumentID, arg.CollaboratorID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO Documents(title, author_id)
VALUES ($1, $2)
RETURNING id, title, number_of_collaborators, current_version, author_id
`

type CreateDocumentParams struct {
	Title    string
	AuthorID uuid.NullUUID
}

type CreateDocumentRow struct {
	ID                    uuid.UUID
	Title                 string
	NumberOfCollaborators int32
	CurrentVersion        sql.NullInt32
	AuthorID              uuid.NullUUID
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, createDocument, arg.Title, arg.AuthorID)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.NumberOfCollaborators,
		&i.CurrentVersion,
		&i.AuthorID,
	)
	return i, err
}

const getDocumentCollaborators = `-- name: GetDocumentCollaborators :many
SELECT u.id , u.username
FROM DocumentCollaborators dc
JOIN Users u ON dc.collaborator_id =  u.id
WHERE dc.document_id = $1
`

type GetDocumentCollaboratorsRow struct {
	ID       uuid.UUID
	Username string
}

func (q *Queries) GetDocumentCollaborators(ctx context.Context, documentID uuid.NullUUID) ([]GetDocumentCollaboratorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentCollaborators, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentCollaboratorsRow
	for rows.Next() {
		var i GetDocumentCollaboratorsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyCollaborations = `-- name: GetMyCollaborations :many
SELECT d.id , d.title
FROM Documents d
JOIN DocumentCollaborators dc ON d.id = dc.document_id
WHERE dc.collaborator_id = $1
`

type GetMyCollaborationsRow struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) GetMyCollaborations(ctx context.Context, collaboratorID uuid.NullUUID) ([]GetMyCollaborationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMyCollaborations, collaboratorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyCollaborationsRow
	for rows.Next() {
		var i GetMyCollaborationsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyDocuments = `-- name: GetMyDocuments :many
SELECT id, title
FROM Documents 
WHERE author_id = $1
`

type GetMyDocumentsRow struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) GetMyDocuments(ctx context.Context, authorID uuid.NullUUID) ([]GetMyDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMyDocuments, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyDocumentsRow
	for rows.Next() {
		var i GetMyDocumentsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
