// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO Operations(operation_type, document_id, operation_by, position, content, length)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING 1
`

type CreateOperationParams struct {
	OperationType OperationType
	DocumentID    uuid.NullUUID
	OperationBy   uuid.NullUUID
	Position      int32
	Content       string
	Length        int32
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createOperation,
		arg.OperationType,
		arg.DocumentID,
		arg.OperationBy,
		arg.Position,
		arg.Content,
		arg.Length,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
