###
# router.Get("/", func(w http.ResponseWriter, r *http.Request) {
#		w.Write([]byte("Hello World with middlewares"))
#	})
GET http://localhost:8000/



###
#
# router.Post("/signup", handlers.SignupHandler(&apiCfg))
POST http://localhost:8000/signup
accept: application/json
content-type: application/json
Origin: http://localhost:3000

{
  "username": "TestUser",
  "email": "test13@gmail.com",
  "password": "test123"
}

###
# router.Post("/login", handlers.LoginHandler(&apiCfg))
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YzUwZTc4LWZlYjMtNGE1My1hOTBiLWJjNmU5NThiMGRmMiIsImV4cCI6MTczNjY2Nzg3NX0.xCyMcVXzrvOo-cenNE0mS57m8NsXLOXf3IBykIVpmUk
POST http://localhost:8000/login
accept: application/json
content-type: application/json

{
  "email": "test13@gmail.com",
  "password": "test123"
}

###
# router.Post("/create-doc", handlers.CreateDocumentHandler(&apiCfg))
POST http://localhost:8000/create-doc
Accept: application/json
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2ZDQ4NzM5LWQwODctNDcyYi1hODBiLTdhNzM4YmMzYjZlYyIsImV4cCI6MTczNjE5OTU0N30.KY2k3KkFl-xG6s0xAe87UNJ2-uXf7jRG_mn5uBMlmq8 

{
  "title": "MyFirstDoc"
}

###
# router.Post("/get-my-docs", handlers.CreateDocumentHandler(&apiCfg))
GET http://localhost:8000/get-my-docs
Accept: application/json
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2ZDQ4NzM5LWQwODctNDcyYi1hODBiLTdhNzM4YmMzYjZlYyIsImV4cCI6MTczNjQ0NDg1OH0.buB2z2obRgxX4kHs5Am8YJm74ToTOG4lpfjvvJaQusQ
 
###
# router.Post("/get-my-collabs", handlers.CreateDocumentHandler(&apiCfg))
GET http://localhost:8000/get-my-collabs
Accept: application/json
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlNGYzMDc1LTJhNTEtNGE0Yy1hOWZiLTVmMDgyOTU1N2EyNCIsImV4cCI6MTczNjE3MjA2Nn0.VskvjQbDphryH7Ze7xTOHIpDaAQkzXeDHDaSup3B88U

###
# router.Post("/get-document-collabs", handlers.CreateDocumentHandler(&apiCfg))
POST http://localhost:8000/get-document-collabs
Accept: application/json
content-type: application/json

{
  "document_id": "3de3b255-78c4-4762-b9df-d2cf45e404ae"
}

###
# router.With(middlewares.AuthMiddleware).Post("/add-collab", handlers.AddDocumentCollaborator(&apiCfg))
POST http://localhost:8000/add-collab
Accept: application/json
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlNGYzMDc1LTJhNTEtNGE0Yy1hOWZiLTVmMDgyOTU1N2EyNCIsImV4cCI6MTczNjE3MjA2Nn0.VskvjQbDphryH7Ze7xTOHIpDaAQkzXeDHDaSup3B88U

{
  "document_id": "3de3b255-78c4-4762-b9df-d2cf45e404ae",
  "collaborator_id": "c5227964-8961-4acc-90e7-3788a204ea98"
}

###
#
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2ZDQ4NzM5LWQwODctNDcyYi1hODBiLTdhNzM4YmMzYjZlYyIsImV4cCI6MTczNjQ0NDg1OH0.buB2z2obRgxX4kHs5Am8YJm74ToTOG4lpfjvvJaQusQ
#27e7142d-1911-433a-96cd-b6c652482403
#b6d48739-d087-472b-a80b-7a738bc3b6ec
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzVlMDAzLWMwNDAtNDFmOS1iY2E0LWRjMmU4ZmE1YmU0NyIsImV4cCI6MTczNjQ0NDk0Mn0.c0B2SsFwS-YCIQO6tuetMXwq-v1LT29ZgEQRPtuhX2Q
#5f75e003-c040-41f9-bca4-dc2e8fa5be47
#router.Post("/get-document-operations", handlers.GetDocumentOperationsHandler(&apiCfg))
POST http://localhost:8000/get-document-operations
Accept: application/json
content-type: application/json

{
  "document_id": "27e7142d-1911-433a-96cd-b6c652482403"
} 



###
#router.With(middlewares.AuthMiddleware).Get("/get-doc", handlers.GetDocumentFromId(&apiCfg))
GET http://localhost:8000/get-document-operations
Accept: application/json
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNhNjY2ODVhLTZkY2EtNDRkZS05ZGFlLTgwNDc0ZTkzOWVmNyIsImV4cCI6MTczOTExMzI4OX0.mRzlmLpfh1X-Pfcm502FWPDGu1phZQpAVGdnV2y54LA

{
  "document_id": "27e7142d-1911-433a-96cd-b6c652482403"
} 
